// Weight conversion program for Mars&Moon
let earth_weight = 75;//your weight
let destination_weight = earth_weight * 0.38; // formula for Mars
let destination_weight_moon = earth_weight / 6 ; // formula for moon
console.log('Your weight on Earth is', earth_weight,'pounds.') ;
console.log('Your weight on Mars is ',destination_weight,'pounds.' );
console.log('Your weight on moon is',destination_weight_moon,'pounds.')